[NPC]
;DEFAULT: NPC默认的名字颜色
DEFAULT=0xFF00FF00

;TARGET: 鼠标指向的NPC的名字颜色
TARGET=0xFF00FF00

;BOSS_NORMAL: BOSS(小)的名字颜色
;BOSS_POWERFUL: BOSS(大)的名字颜色
BOSS_NORMAL=0xFF5e88FF
BOSS_POWERFUL=0xFFFF8000

;LEVEL_DIFF_*: NPC名字等级颜色(相对玩家本人的级别差，名字颜色)
LEVEL_DIFF_1=-9999999,0xFFC8C8C8
LEVEL_DIFF_2=-8,0xFFFFFFFF
LEVEL_DIFF_3=5,0xFFF22123


[PLAYER]
;FACTION_NONE: 玩家(无门派)的名字颜色
FACTION_NONE=0xFFFFFFFF

;FACTION_BELONG: 玩家(有门派)的名字颜色
FACTION_BELONG=0xFF95FF95

;队友
TEAM_MEMBER=0xFF7197FF

;PK阵营1
PK_FIGHT_1=0xFFFFCE15
;PK阵营2
PK_FIGHT_2=0xFFFF82FF
;PK阵营3
PK_FIGHT_3=0xFF00E4FF

;帮战
; TONG_FIGHT=0xFF9400D3
TONG_FIGHT=0xFF95FF95

;盟友
FRIEND=0xFF7197FF

;敌人
ENEMY=0xFFFF3333
;ENEMY=0xFFFF0000
;ENEMY=0xFFCC6600

;盟友中的队友
FRIENDTEAMMATE=0xFFFFCE15

;FRIEND: PLAYER的盟友目标
FRIEND=0xFF95FF95

;SAMECAMP: PLAYER的同阵营
SAMECAMP=0xFF95FF95

;TEAMMATE: PLAYER的队友
TEAMMATE=0xFF95FF95

;DESALT: PLAYER没有流派和隐藏名字颜色的名字颜色
DESALT=0xFFFFFFFF