TMZ_ShowData = {
	[35] = {
		["title"] = {
			[1] = "Tªn",
			[2] = "Phe",
			[3] = "L­u ph¸i",
			[4] = "GiÕt",
			[5] = "ChÕt",
			[6] = "TrËn nh·n",
		},
		["name"] = "Thiªn M«n trËn",
		["szFormat"] = "%-17s%-10s%-16s%-9s%-9s%-10s",
		["szMsg"] = "Tû lÖ chiÕm trËn: <color=yellow>Qu©n Tèng[0]<color>: <color=pink>[0]Qu©n Liªu<color>",
		["data"] = {
			["ParkBongPal"] = {
				[1] = "ParkBongPal",
				[2] = "Qu©n Tèng",
				[3] = "ThiÕu L©m vâ t¨ng",
				[4] = 0,
				[5] = 0,
				[6] = 0,
				[7] = 48,
				[8] = "<color=yellow>",
			},
			["1ThêiOanhLiÖt"] = {
				[1] = "1ThêiOanhLiÖt",
				[2] = "Qu©n Tèng",
				[3] = "ThiÕu L©m vâ t¨ng",
				[4] = 0,
				[5] = 0,
				[6] = 0,
				[7] = 55,
				[8] = "<color=yellow>",
			},
			["iHPGaTapViet"] = {
				[1] = "iHPGaTapViet",
				[2] = "Qu©n Liªu",
				[3] = "Minh Gi¸o TrËn Binh",
				[4] = 0,
				[5] = 0,
				[6] = 0,
				[7] = 65,
				[8] = "<color=pink>",
			},
			["parent"] = 1,
		},
	},
	["title"] = {
		[1] = "Tªn",
		[2] = "Phe",
		[3] = "L­u ph¸i",
		[4] = "GiÕt",
		[5] = "ChÕt",
		[6] = "TrËn nh·n",
	},
	["name"] = "Thiªn M«n trËn",
	["szFormat"] = "%-17s%-10s%-16s%-9s%-9s%-10s",
	["CurN"] = 352,
}
