[Main]
;ËùÓĞ¼¼ÄÜ¿ÉÒÔµôÂäµÄÎïÆ·×ÜÊı
DropItemCount=124


;ÒÔÏÂÎª½ğÊô
;µôÂäµÄÎïÆ·1µÄÉè¶¨
;[1]
;µôÂäÎïÆ·1µÄ´óÀà
;Gene=2
;µôÂäÎïÆ·1µÄ¸±Àà
;Sub=2
;µôÂäÎïÆ·1µÄÏêÏ¸Àà±ğ
;Detail=1

;ËÉÄ¾ skil:1 lvl:1
[1]
Gene=2
Sub=2
Detail=41

;ÑîÄ¾ skil:1 lvl:1
[2]
Gene=2
Sub=2
Detail=42

;É¼Ä¾ skil:1 lvl:1
[3]
Gene=2
Sub=2
Detail=43

;ÌúÄ¾ skil:1 lvl:1
[4]
Gene=2
Sub=2
Detail=44

;ÎàÍ©Ä¾ skil:1 lvl:2
[5]
Gene=2
Sub=2
Detail=45

;ÖØÄ¾ skil:1 lvl:2
[6]
Gene=2
Sub=2
Detail=9

;ÌúÕÁÄ¾ skil:1 lvl:2
[7]
Gene=2
Sub=2
Detail=10

;ÌúèëÄ¾ skil:1 lvl:2
[8]
Gene=2
Sub=2
Detail=104

;ÌúÏßÄ¾ skil:1 lvl:3
[9]
Gene=2
Sub=2
Detail=11

;²¨ÂŞÄ¾ skil:1 lvl:3
[10]
Gene=2
Sub=2
Detail=12

;Ì´Ä¾ skil:1 lvl:3
[11]
Gene=2
Sub=2
Detail=13

;ÆĞÌáÄ¾ skil:1 lvl:3
[12]
Gene=2
Sub=2
Detail=14

;½¨Ä¾ skil:1 lvl:3
[13]
Gene=2
Sub=2
Detail=105

;ÓñÊ÷¸É skil:1 lvl:4
[14]
Gene=2
Sub=7
Detail=3

;ÆÅÂŞÄ¾¸É skil:1 lvl:4
[15]
Gene=2
Sub=7
Detail=6

;ÆĞÌáÄ¾¸É skil:1 lvl:4
[16]
Gene=2
Sub=7
Detail=7

;ºÚÈ®ÁéÑª skil:2 lvl:1
[17]
Gene=2
Sub=2
Detail=33

;ÇàÎÚÁéÑª skil:2 lvl:1
[18]
Gene=2
Sub=2
Detail=34

;Ğşº×ÁéÑª skil:2 lvl:1
[19]
Gene=2
Sub=2
Detail=35

;ÍÃÃ« skil:2 lvl:1
[20]
Gene=2
Sub=9
Detail=1

;ÀÇÆ¤ skil:2 lvl:1
[21]
Gene=2
Sub=2
Detail=15

;»¢Æ¤ skil:2 lvl:1
[22]
Gene=2
Sub=2
Detail=16

;ÉßÆ¤ skil:2 lvl:1
[23]
Gene=2
Sub=2
Detail=18

;ÍÃÈâ skil:2 lvl:1
[24]
Gene=1
Sub=3
Detail=1

;¼¦Èâ skil:2 lvl:1
[25]
Gene=1
Sub=3
Detail=2

;ºüÆ¤ skil:2 lvl:2
[26]
Gene=2
Sub=2
Detail=17

;°×»¢Æ¤ skil:2 lvl:2
[27]
Gene=2
Sub=2
Detail=19

;ĞÜÕÆ skil:2 lvl:2
[28]
Gene=1
Sub=3
Detail=4

;°×»¢Ö®Æ¤ skil:2 lvl:2
[29]
Gene=2
Sub=2
Detail=46

;ĞÜÆ¤ skil:2 lvl:2
[30]
Gene=2
Sub=2
Detail=20

;ğ½ÄñÓğÅû skil:2 lvl:2
[31]
Gene=2
Sub=10
Detail=7

;ÂÊÈ»Ô­Æ¤ skil:2 lvl:3
[32]
Gene=2
Sub=10
Detail=2

;É½Ê¨Ö®Æ¤ skil:2 lvl:3
[33]
Gene=2
Sub=2
Detail=47

;ÖìÈ¸Ö®Óğ skil:2 lvl:3
[34]
Gene=2
Sub=2
Detail=49

;Áé÷¡Ö®Æ¤ skil:2 lvl:3
[35]
Gene=2
Sub=2
Detail=50

;µØÁúÑª skil:2 lvl:3
[36]
Gene=2
Sub=2
Detail=107

;°ÍÉßÔ­Æ¤ skil:2 lvl:4
[37]
Gene=2
Sub=10
Detail=3

;°×Ô³Ö®Æ¤ skil:2 lvl:4
[38]
Gene=2
Sub=2
Detail=48

;ÔÌÁéºÁ skil:2 lvl:4
[39]
Gene=2
Sub=2
Detail=109

;²ÏË¿ skil:3 lvl:1
[40]
Gene=2
Sub=9
Detail=2

;ÎåÉ«Ë¿ skil:3 lvl:1
[41]
Gene=2
Sub=9
Detail=3

;ºì¸ßÁ» skil:3 lvl:1
[42]
Gene=1
Sub=3
Detail=5

;¹âÍ¨Âé skil:3 lvl:1
[43]
Gene=1
Sub=3
Detail=9

;ÇãÀé¶¹ skil:3 lvl:1
[44]
Gene=1
Sub=3
Detail=10

;ÈÆÃ÷¶¹ skil:3 lvl:1
[45]
Gene=1
Sub=3
Detail=11

;Ä¾¶ú skil:3 lvl:1
[46]
Gene=1
Sub=3
Detail=19

;Ê¯¾ú skil:3 lvl:1
[47]
Gene=1
Sub=3
Detail=20

;ÖñÈâ skil:3 lvl:1
[48]
Gene=1
Sub=3
Detail=21

;ÀÇÖëË¿ skil:3 lvl:2
[49]
Gene=2
Sub=2
Detail=52

;Ñª²ÏË¿ skil:3 lvl:2
[50]
Gene=2
Sub=2
Detail=53

;ÁéÖëË¿ skil:3 lvl:2
[51]
Gene=2
Sub=2
Detail=54

;½ğ²ÏË¿ skil:3 lvl:2
[52]
Gene=2
Sub=2
Detail=55

;½ğÊµµ¾ skil:3 lvl:2
[53]
Gene=1
Sub=3
Detail=6

;ÈÚÔó¹È skil:3 lvl:2
[54]
Gene=1
Sub=3
Detail=12

;¸ÊÕá skil:3 lvl:2
[55]
Gene=1
Sub=3
Detail=13

;ÑÓ¾«Âó skil:3 lvl:2
[56]
Gene=1
Sub=3
Detail=14

;´¾ºÍÂó skil:3 lvl:2
[57]
Gene=1
Sub=3
Detail=15

;ºú½· skil:3 lvl:2
[58]
Gene=1
Sub=3
Detail=22

;Àä³æË¿ skil:3 lvl:3
[59]
Gene=2
Sub=9
Detail=4

;»ğÖëË¿ skil:3 lvl:3
[60]
Gene=2
Sub=9
Detail=5

;±ù²ÏË¿ skil:3 lvl:3
[61]
Gene=2
Sub=9
Detail=6

;ÎÚ²ÏË¿ skil:3 lvl:3
[62]
Gene=2
Sub=9
Detail=7

;Ìì²ÏË¿ skil:3 lvl:3
[63]
Gene=2
Sub=2
Detail=56

;²ÊÔÆË¿ skil:3 lvl:3
[64]
Gene=2
Sub=2
Detail=100

;ÓÎÁúËÚ skil:3 lvl:3
[65]
Gene=1
Sub=3
Detail=16

;·ï¹ÚËÚ skil:3 lvl:3
[66]
Gene=1
Sub=3
Detail=17

;Ò¡Ö¦ËÚ skil:3 lvl:3
[67]
Gene=1
Sub=3
Detail=18

;ÈğÂó skil:3 lvl:4
[68]
Gene=2
Sub=130
Detail=20

;°ëÏÄµ¾ skil:3 lvl:4
[69]
Gene=2
Sub=130
Detail=21

;Öñİ¥ skil:3 lvl:4
[70]
Gene=2
Sub=130
Detail=22

;²Øºì»¨ skil:4 lvl:1
[71]
Gene=1
Sub=2
Detail=1

;½Û¹£ skil:4 lvl:1
[72]
Gene=1
Sub=2
Detail=2

;°Í¶¹ skil:4 lvl:1
[73]
Gene=1
Sub=2
Detail=8

;»ÆÁ¬ skil:4 lvl:2
[74]
Gene=1
Sub=2
Detail=3

;²õÍÉ skil:4 lvl:2
[75]
Gene=1
Sub=2
Detail=9

;ÌïÆß skil:4 lvl:2
[76]
Gene=1
Sub=2
Detail=10

;´©É½¼× skil:4 lvl:2
[77]
Gene=1
Sub=2
Detail=11

;Ñ©Á«×Ó skil:4 lvl:2
[78]
Gene=1
Sub=2
Detail=12

;÷êÏã skil:4 lvl:3
[79]
Gene=1
Sub=2
Detail=4

;ÈË²Î skil:4 lvl:3
[80]
Gene=1
Sub=2
Detail=5

;ĞÜµ¨ skil:4 lvl:3
[81]
Gene=1
Sub=2
Detail=6

;³æ²İ skil:4 lvl:4
[82]
Gene=2
Sub=130
Detail=24

;ºÎÊ×ÎÚ skil:4 lvl:4
[83]
Gene=2
Sub=130
Detail=25

;ÌìÂé skil:4 lvl:4
[84]
Gene=2
Sub=130
Detail=26

;¾«Ìú skil:5 lvl:1
[85]
Gene=2
Sub=2
Detail=1

;°ÙÁ¶¸Ö skil:5 lvl:1
[86]
Gene=2
Sub=2
Detail=2

;ÎÚ½ğÊ¯ skil:5 lvl:1
[87]
Gene=2
Sub=8
Detail=5

;×Ï½ğ skil:5 lvl:1
[88]
Gene=2
Sub=2
Detail=3

;ÖìÉ° skil:5 lvl:1
[89]
Gene=2
Sub=2
Detail=30

;º®Ìú skil:5 lvl:2
[90]
Gene=2
Sub=2
Detail=4

;Ì«°×¾«½ğ skil:5 lvl:2
[91]
Gene=2
Sub=2
Detail=5

;ĞşÌú skil:5 lvl:2
[92]
Gene=2
Sub=2
Detail=6

;ÌìÇàÊ¯ skil:5 lvl:2
[93]
Gene=2
Sub=2
Detail=36

;µ¤ĞÄÉ° skil:5 lvl:2
[94]
Gene=2
Sub=2
Detail=31

;±ÌÑªÉ° skil:5 lvl:2
[95]
Gene=2
Sub=2
Detail=32

;ĞşÊ¯ skil:5 lvl:3
[96]
Gene=2
Sub=8
Detail=7

;ºÚÎÙÊ¯ skil:5 lvl:3
[97]
Gene=2
Sub=2
Detail=37

;³àÌú skil:5 lvl:3
[98]
Gene=2
Sub=2
Detail=38

;ÔÆÄ¸ skil:5 lvl:3
[99]
Gene=2
Sub=2
Detail=39

;ÌìÁéÉ° skil:5 lvl:3
[100]
Gene=2
Sub=2
Detail=106

;×ÏÊ¯Ó¢ skil:5 lvl:4
[101]
Gene=2
Sub=130
Detail=16

;ï¯Ê¯ skil:5 lvl:4
[102]
Gene=2
Sub=2
Detail=40

;´ß»êÉ° skil:5 lvl:4
[103]
Gene=2
Sub=130
Detail=17

;öÔÓã skil:6 lvl:1
[104]
Gene=1
Sub=3
Detail=3

;ÀğÓã skil:6 lvl:1
[105]
Gene=2
Sub=130
Detail=1

;¹ğÓã skil:6 lvl:1
[106]
Gene=2
Sub=130
Detail=2

;°×ÕäÖé skil:6 lvl:1
[107]
Gene=2
Sub=130
Detail=3

;öóÓã skil:6 lvl:2
[108]
Gene=2
Sub=130
Detail=4

;ºÚÓã skil:6 lvl:2
[109]
Gene=2
Sub=130
Detail=5

;öêÓã skil:6 lvl:2
[110]
Gene=2
Sub=130
Detail=6

;ºÚÕäÖé skil:6 lvl:2
[111]
Gene=2
Sub=130
Detail=7

;»ÆÓã skil:6 lvl:3
[112]
Gene=2
Sub=130
Detail=8

;Ğ· skil:6 lvl:3
[113]
Gene=2
Sub=130
Detail=9

;Ïº skil:6 lvl:3
[114]
Gene=2
Sub=130
Detail=10

;ºÓëà skil:6 lvl:3
[115]
Gene=2
Sub=130
Detail=11

;öãÓã skil:6 lvl:4
[116]
Gene=2
Sub=130
Detail=12

;ºìÉºº÷Öé skil:6 lvl:4
[117]
Gene=2
Sub=130
Detail=13

;À¶Éºº÷Öé skil:6 lvl:4
[118]
Gene=2
Sub=130
Detail=14

ÒÔÏÂÎªÈÎÎñÎïÆ·
[119]
Gene=2
Sub=0
Detail=126
TaskID=1931

[120]
Gene=2
Sub=0
Detail=127
TaskID=1931

[121]
Gene=2
Sub=0
Detail=129
TaskID=1931

[122]
Gene=2
Sub=0
Detail=130
TaskID=1931

[123]
Gene=2
Sub=0
Detail=132
TaskID=1931

[124]
Gene=2
Sub=0
Detail=133
TaskID=1931