Import("\\script\\ksgvn\\constants.lua")

g_tbAccounts_Admin = { 'tk1', 'tk2', }
g_tbAccounts_GM = { 'tk1', 'tk2'}
g_tbFactionRoutes = {
    ROUTE_THIEULAM_DAO,
    ROUTE_THIEULAM_TRUONG,
    ROUTE_THIEULAM_QUYEN,
    ROUTE_DUONGMON_AMKHI,
    ROUTE_NGAMI_KIEM,
    ROUTE_NGAMI_DAN,
    ROUTE_CAIBANG_QUYEN,
    ROUTE_CAIBANG_BONG,
    ROUTE_VODANG_KIEM,
    ROUTE_VODANG_BUT,
    ROUTE_DUONGGIA_THUONG,
    ROUTE_DUONGGIA_CUNG,
    ROUTE_NGUDOC_HIEP,
    ROUTE_NGUDOC_TA,
    ROUTE_CONLON_THIENSU,
    ROUTE_MINHGIAO_THANHCHIEN,
    ROUTE_MINHGIAO_TRANBINH,
    ROUTE_MINHGIAO_HUYETNHAN,
    ROUTE_THUYYEN_VUTIEN,
    ROUTE_THUYYEN_LINHNU,
    ROUTE_DUONGMON_NHAMHIEP,
    ROUTE_CONLON_KIEMTON,
}

g_tbFactionRoutes_Offset = {
    [ROUTE_THIEULAM_DAO] = 0,
    [ROUTE_THIEULAM_TRUONG] = 2,
    [ROUTE_THIEULAM_QUYEN] = 4,
    [ROUTE_DUONGMON_AMKHI] = 6,
    [ROUTE_NGAMI_KIEM] = 10,
    [ROUTE_NGAMI_DAN] = 12,
    [ROUTE_CAIBANG_QUYEN] = 14,
    [ROUTE_CAIBANG_BONG] = 18,
    [ROUTE_VODANG_KIEM] = 22,
    [ROUTE_VODANG_BUT] = 26,
    [ROUTE_DUONGGIA_THUONG] = 30,
    [ROUTE_DUONGGIA_CUNG] = 34,
    [ROUTE_NGUDOC_HIEP] = 38,
    [ROUTE_NGUDOC_TA] = 42,
    [ROUTE_CONLON_THIENSU] = 46,
    [ROUTE_MINHGIAO_THANHCHIEN] = 48,
    [ROUTE_MINHGIAO_TRANBINH] = 52,
    [ROUTE_MINHGIAO_HUYETNHAN] = 56,
    [ROUTE_THUYYEN_VUTIEN] = 60,
    [ROUTE_THUYYEN_LINHNU] = 62,
    [ROUTE_DUONGMON_NHAMHIEP] = 64,
    [ROUTE_CONLON_KIEMTON] = 68,
}

g_tbFactionRoute_WeaponTypes = {
    [ROUTE_THIEULAM_DAO] = WEAPON_TYPE_DAO,
    [ROUTE_THIEULAM_TRUONG] = WEAPON_TYPE_TRUONG,
    [ROUTE_THIEULAM_QUYEN] = WEAPON_TYPE_BAOTAY,
    [ROUTE_DUONGMON_AMKHI] = WEAPON_TYPE_CHAM,
    [ROUTE_NGAMI_KIEM] = WEAPON_TYPE_KIEM,
    [ROUTE_NGAMI_DAN] = WEAPON_TYPE_DAN,
    [ROUTE_CAIBANG_QUYEN] = WEAPON_TYPE_BAOTAY,
    [ROUTE_CAIBANG_BONG] = WEAPON_TYPE_CON,
    [ROUTE_VODANG_KIEM] = WEAPON_TYPE_KIEM,
    [ROUTE_VODANG_BUT] = WEAPON_TYPE_BUT,
    [ROUTE_DUONGGIA_THUONG] = WEAPON_TYPE_THUONG,
    [ROUTE_DUONGGIA_CUNG] = WEAPON_TYPE_CUNG,
    [ROUTE_NGUDOC_HIEP] = WEAPON_TYPE_SONGDAO,
    [ROUTE_NGUDOC_TA] = WEAPON_TYPE_TRAO,
    [ROUTE_CONLON_THIENSU] = WEAPON_TYPE_KIEM,
    [ROUTE_MINHGIAO_THANHCHIEN] = WEAPON_TYPE_DAO,
    [ROUTE_MINHGIAO_TRANBINH] = WEAPON_TYPE_BUT,
    [ROUTE_MINHGIAO_HUYETNHAN] = WEAPON_TYPE_TRAO,
    [ROUTE_THUYYEN_VUTIEN] = WEAPON_TYPE_VUTIEN,
    [ROUTE_THUYYEN_LINHNU] = WEAPON_TYPE_LINHNU,
    [ROUTE_DUONGMON_NHAMHIEP] = WEAPON_TYPE_NHAMHIEP,
    [ROUTE_CONLON_KIEMTON] = WEAPON_TYPE_KIEM,
}

g_tbFactionRoute_Names = {
    [ROUTE_VOMONPHAI] = "V« m«n phži",
    [ROUTE_THIEULAM] = "ThiÕu L©m",
    [ROUTE_THIEULAM_DAO] = "ThiÕu L©m §ao",
    [ROUTE_THIEULAM_TRUONG] = "ThiÕu L©m Tr­îng",
    [ROUTE_THIEULAM_QUYEN] = "ThiÕu L©m QuyÒn",
    [ROUTE_DUONGMON] = "§­êng M«n",
    [ROUTE_DUONGMON_AMKHI] = "§­êng M«n Ch©m",
    [ROUTE_NGAMI] = "Nga My",
    [ROUTE_NGAMI_KIEM] = "Nga My KiÕm",
    [ROUTE_NGAMI_DAN] = "Nga My §µn",
    [ROUTE_CAIBANG] = "Cži Bang",
    [ROUTE_CAIBANG_QUYEN] = "Cži Bang QuyÒn",
    [ROUTE_CAIBANG_BONG] = "Cži Bang Bæng",
    [ROUTE_VODANG] = "Vâ §ang",
    [ROUTE_VODANG_KIEM] = "Vâ §ang KiÕm",
    [ROUTE_VODANG_BUT] = "Vâ §ang Bót",
    [ROUTE_DUONGGIA] = "D­¬ng M«n",
    [ROUTE_DUONGGIA_THUONG] = "D­¬ng Gia Th­¬ng",
    [ROUTE_DUONGGIA_CUNG] = "D­¬ng Gia Cung",
    [ROUTE_NGUDOC] = "Ngò §éc",
    [ROUTE_NGUDOC_HIEP] = "HiÖp §éc",
    [ROUTE_NGUDOC_TA] = "Tµ §éc",
    [ROUTE_CONLON] = "C«n L«n",
    [ROUTE_CONLON_THIENSU] = "C«n L«n Thiªn S­",
    [ROUTE_MINHGIAO] = "Minh Gižo",
    [ROUTE_MINHGIAO_THANHCHIEN] = "Minh Gižo Thžnh ChiÕn",
    [ROUTE_MINHGIAO_TRANBINH] = "Minh Gižo TrËn Binh",
    [ROUTE_MINHGIAO_HUYETNHAN] = "Minh Gižo HuyÕt Nh©n",
    [ROUTE_THUYYEN] = "Thóy Yªn",
    [ROUTE_THUYYEN_VUTIEN] = "Thóy Yªn Vò Tiªn",
    [ROUTE_THUYYEN_LINHNU] = "Thóy Yªn Linh N÷",
    [ROUTE_DUONGMON_NHAMHIEP] = "§­êng M«n NhËm HiÖp",
    [ROUTE_CONLON_KIEMTON] = "C«n L«n KiÕm T«n",
}

g_tbFactionRoute_Types = {
    [ROUTE_THIEULAM_DAO] = DAME_TYPE_NGOAICONG,
    [ROUTE_THIEULAM_TRUONG] = DAME_TYPE_NOICONG,
    [ROUTE_THIEULAM_QUYEN] = DAME_TYPE_NOICONG,
    [ROUTE_DUONGMON_AMKHI] = DAME_TYPE_SATTHUONG,
    [ROUTE_NGAMI_KIEM] = DAME_TYPE_NOICONG,
    [ROUTE_NGAMI_DAN] = DAME_TYPE_CAM,
    [ROUTE_CAIBANG_QUYEN] = DAME_TYPE_NGOAICONG,
    [ROUTE_CAIBANG_BONG] = DAME_TYPE_SATTHUONG,
    [ROUTE_VODANG_KIEM] = DAME_TYPE_NOICONG,
    [ROUTE_VODANG_BUT] = DAME_TYPE_SATTHUONG,
    [ROUTE_DUONGGIA_THUONG] = DAME_TYPE_NGOAICONG,
    [ROUTE_DUONGGIA_CUNG] = DAME_TYPE_SATTHUONG,
    [ROUTE_NGUDOC_HIEP] = DAME_TYPE_SATTHUONG,
    [ROUTE_NGUDOC_TA] = DAME_TYPE_SATTHUONG,
    [ROUTE_CONLON_THIENSU] = DAME_TYPE_NOICONG,
    [ROUTE_MINHGIAO_THANHCHIEN] = DAME_TYPE_NGOAICONG,
    [ROUTE_MINHGIAO_TRANBINH] = DAME_TYPE_NGOAICONG,
    [ROUTE_MINHGIAO_HUYETNHAN] = DAME_TYPE_NOICONG,
    [ROUTE_THUYYEN_VUTIEN] = DAME_TYPE_NGOAICONG,
    [ROUTE_THUYYEN_LINHNU] = DAME_TYPE_SATTHUONG,
    [ROUTE_DUONGMON_NHAMHIEP] = DAME_TYPE_NGOAICONG,
    [ROUTE_CONLON_KIEMTON] = DAME_TYPE_NGOAICONG,
}

g_tbFactionRoute_Genres = {
    [ROUTE_THIEULAM_DAO] = 1,
    [ROUTE_THIEULAM_TRUONG] = 3,
    [ROUTE_THIEULAM_QUYEN] = 3,
    [ROUTE_DUONGMON_AMKHI] = 2,
    [ROUTE_NGAMI_KIEM] = 3,
    [ROUTE_NGAMI_DAN] = 2,
    [ROUTE_CAIBANG_QUYEN] = 1,
    [ROUTE_CAIBANG_BONG] = 2,
    [ROUTE_VODANG_KIEM] = 3,
    [ROUTE_VODANG_BUT] = 2,
    [ROUTE_DUONGGIA_THUONG] = 1,
    [ROUTE_DUONGGIA_CUNG] = 1,
    [ROUTE_NGUDOC_HIEP] = 2,
    [ROUTE_NGUDOC_TA] = 3,
    [ROUTE_CONLON_THIENSU] = 3,
    [ROUTE_MINHGIAO_THANHCHIEN] = 1,
    [ROUTE_MINHGIAO_TRANBINH] = 1,
    [ROUTE_MINHGIAO_HUYETNHAN] = 2,
    [ROUTE_THUYYEN_VUTIEN] = 2,
    [ROUTE_THUYYEN_LINHNU] = 2,
    [ROUTE_DUONGMON_NHAMHIEP] = 1,
    [ROUTE_CONLON_KIEMTON] = 3,
}

-- 0 = Ca 2, 1 = Nam, 2 = Nu
g_tbFactionRoute_Gender = {
    [ROUTE_THIEULAM_DAO] = 1,
    [ROUTE_THIEULAM_TRUONG] = 1,
    [ROUTE_THIEULAM_QUYEN] = 1,
    [ROUTE_DUONGMON_AMKHI] = 0,
    [ROUTE_NGAMI_KIEM] = 2,
    [ROUTE_NGAMI_DAN] = 2,
    [ROUTE_CAIBANG_QUYEN] = 0,
    [ROUTE_CAIBANG_BONG] = 0,
    [ROUTE_VODANG_KIEM] = 0,
    [ROUTE_VODANG_BUT] = 0,
    [ROUTE_DUONGGIA_THUONG] = 0,
    [ROUTE_DUONGGIA_CUNG] = 0,
    [ROUTE_NGUDOC_HIEP] = 0,
    [ROUTE_NGUDOC_TA] = 0,
    [ROUTE_CONLON_THIENSU] = 1,
    [ROUTE_MINHGIAO_THANHCHIEN] = 0,
    [ROUTE_MINHGIAO_TRANBINH] = 0,
    [ROUTE_MINHGIAO_HUYETNHAN] = 0,
    [ROUTE_THUYYEN_VUTIEN] = 2,
    [ROUTE_THUYYEN_LINHNU] = 2,
    [ROUTE_DUONGMON_NHAMHIEP] = 0,
    [ROUTE_CONLON_KIEMTON] = 1,
}

g_tbFactionRoute_Skill = {
    [ROUTE_THIEULAM_DAO] = { nBegin = 21, nEnd = 31, tbDefault = { 3, 5 }, nSkill55 = 31, nTranPhai = 32, tbMonsters = { 2359, 2360, 2361 }, },
    [ROUTE_THIEULAM_TRUONG] = { nBegin = 45, nEnd = 56, tbDefault = { 6 }, nSkill55 = 56, nTranPhai = 57, tbMonsters = { 2366, 2367, 2368 }, },
    [ROUTE_THIEULAM_QUYEN] = { nBegin = 33, nEnd = 43, tbDefault = { 2 }, nSkill55 = 43, nTranPhai = 44, tbMonsters = { 2374, 2375, 2376 }, },
    [ROUTE_DUONGMON_AMKHI] = { nBegin = 58, nEnd = 73, tbDefault = { 7 }, nSkill55 = 73, nTranPhai = 74, tbMonsters = { 2300, 2301, 2302 }, },
    [ROUTE_NGAMI_KIEM] = { nBegin = 75, nEnd = 88, tbDefault = { 4 }, nSkill55 = 88, nTranPhai = 89, tbMonsters = { 2410, 2411 }, },
    [ROUTE_NGAMI_DAN] = { nBegin = 90, nEnd = 101, tbDefault = { 10 }, nSkill55 = 101, nTranPhai = 102, tbMonsters = { 2403, 2404, 2405 }, },
    [ROUTE_CAIBANG_QUYEN] = { nBegin = 103, nEnd = 112, tbDefault = { 2 }, nSkill55 = 112, nTranPhai = 113, tbMonsters = { 2328, 2329, 2330 }, },
    [ROUTE_CAIBANG_BONG] = { nBegin = 114, nEnd = 123, tbDefault = { 5 }, nSkill55 = 123, nTranPhai = 124, tbMonsters = { 2336, 2337, 2338 }, },
    [ROUTE_VODANG_KIEM] = { nBegin = 125, nEnd = 145, tbDefault = { 4 }, nSkill55 = 145, nTranPhai = 146, tbMonsters = { 2314, 2315, 2316 }, },
    [ROUTE_VODANG_BUT] = { nBegin = 147, nEnd = 158, tbDefault = { 8 }, nSkill55 = 158, nTranPhai = 159, tbMonsters = { 2321, 2322, 2323 }, },
    [ROUTE_DUONGGIA_THUONG] = { nBegin = 720, nEnd = 731, tbDefault = { 11 }, nSkill55 = 731, nTranPhai = 732, tbMonsters = { 2422, 2423, 2424 }, },
    [ROUTE_DUONGGIA_CUNG] = { nBegin = 733, nEnd = 744, tbDefault = { 12 }, nSkill55 = 744, nTranPhai = 745, tbMonsters = { 2415, 2416, 2417 }, },
    [ROUTE_NGUDOC_HIEP] = { nBegin = 364, nEnd = 377, tbDefault = { 13 }, nSkill55 = 377, nTranPhai = 775, tbMonsters = { 2428, 2429, 2430 }, },
    [ROUTE_NGUDOC_TA] = { nBegin = 347, nEnd = 363, tbDefault = { 14 }, nSkill55 = 363, nTranPhai = 774, tbMonsters = { 2438, 2439, 2440 }, },
    [ROUTE_CONLON_THIENSU] = { nBegin = 1017, nEnd = 1031, tbDefault = { 4 }, nSkill55 = 1030, nTranPhai = 1032, tbMonsters = { 2343, 2344, 2345 }, },
    [ROUTE_MINHGIAO_THANHCHIEN] = { nBegin = 1053, nEnd = 1065, tbDefault = { 3 }, nSkill55 = 1065, nTranPhai = 1066, tbMonsters = { 2457, 2458, 2459 }, },
    [ROUTE_MINHGIAO_TRANBINH] = { nBegin = 1083, nEnd = 1095, tbDefault = { 8 }, nSkill55 = 1093, nTranPhai = 1096, tbMonsters = { 2444, 2445, 2446 }, },
    [ROUTE_MINHGIAO_HUYETNHAN] = { nBegin = 1131, nEnd = 1143, tbDefault = { 14 }, nSkill55 = 1143, nTranPhai = 1213, tbMonsters = { 2450, 2451, 2452 }, },
    [ROUTE_THUYYEN_VUTIEN] = { nBegin = 1165, nEnd = 1176, tbDefault = { 15 }, nSkill55 = 1176, nTranPhai = 1196, tbMonsters = { 2396, 2397, 2398 }, },
    [ROUTE_THUYYEN_LINHNU] = { nBegin = 1217, nEnd = 1229, tbDefault = { 16 }, nSkill55 = 1229, nTranPhai = 1230, tbMonsters = { 2381, 2382, 2383 }, },
    [ROUTE_DUONGMON_NHAMHIEP] = { nBegin = 1872, nEnd = 1882, tbDefault = { 17 }, nSkill55 = 1882, nTranPhai = 1883, tbMonsters = { 2307, 2308, 2309 }, },
    [ROUTE_CONLON_KIEMTON] = { nBegin = 1885, nEnd = 1896, tbDefault = { 4 }, nSkill55 = 1896, nTranPhai = 1897, tbMonsters = { 2350, 2351, 2352 }, },
}

g_tbFactionRoute_Females = { ROUTE_NGAMI_KIEM, ROUTE_NGAMI_DAN, ROUTE_THUYYEN_LINHNU, ROUTE_THUYYEN_VUTIEN }

g_tbMeridianNames = {
    "Vâ Gi¶",
    "Vâ T­íng",
    "Vâ V­¬ng",
    "Vâ T«n",
    "Vâ Hoµng",
    "Vâ Thžnh",
}

MAX_EXP = 2e9
MAX_FAIR_LEVEL = 180
MAX_TRANSLIFE = 5

MAX_FACTION_SKILL_LV_55 = 7

SKILL_PET_ID = 30149
