PAGESAY_SELECT_OPTION_PER_PAGE = 6
BATTLE_ITEM_TYPE_SUIT = 1
BATTLE_ITEM_TYPE_SUIT_RING = 2
BATTLE_ITEM_TYPE_SUIT_RING_WEAPON = 3
---- Ext points
EXTPOINT_GIFTCODE_NEWPLAYER = 4

--- STATUS

ADD_ITEM_STATUS_FAILED = 0
ADD_ITEM_STATUS_DROPPED = 2

------- Item Constants
GENRE_ITEM_EQUIP = 0
GENRE_ITEM_USE = 1
GENRE_ITEM_OTHER = 2

----------------
ITEM_OD_QUEST = 0 -- Nhiem vu
ITEM_OD_MYSTERY = 1 -- Vat pham khac
ITEM_OD_ADDENDA = 6 -- Yeu quyet
ITEM_OD_SUMMON = 20 -- Pet
ITEM_OD_GEM = 22 -- Ngoc
-----------------------
EQUIP_TYPE_BODY = 100
EQUIP_TYPE_PANTS = 101
EQUIP_TYPE_RING = 102
EQUIP_TYPE_CAP = 103
EQUIP_TYPE_HORSE = 105
EQUIP_TYPE_PET = 106
EQUIP_TYPE_BOOK = 107
EQUIP_TYPE_COAT_CAP = 108
EQUIP_TYPE_COAT_CLOTH = 109
EQUIP_TYPE_COAT_TROUSERS = 110
EQUIP_TYPE_COAT_SET = 111
EQUIP_TYPE_EXTEND_BOOK = 112
EQUIP_TYPE_ORNAMENT_CAP = 119
EQUIP_TYPE_ORNAMENT_CLOTH = 120
EQUIP_TYPE_ORNAMENT_FOOT = 121

EQUIP_TYPE_CAPE = 152
EQUIP_TYPE_BADGE = 153
EQUIP_TYPE_FOOT = 154

EQUIP_TYPE_TOOL = 200

-------------------------

EQUIP_POS_CAP = 0
EQUIP_POS_BODY = 1
EQUIP_POS_WEAPON = 2
EQUIP_POS_PANTS = 3
EQUIP_POS_RING1 = 4
EQUIP_POS_RING2 = 5
EQUIP_POS_COAT_CAP = 6
EQUIP_POS_COAT_CLOTH = 7
EQUIP_POS_COAT_TROUSERS = 8
EQUIP_POS_EXTEND_BOOK = 9
EQUIP_POS_HORSE = 10
EQUIP_POS_BOOK = 11
EQUIP_POS_EXTEND_WEAPON = 12
EQUIP_POS_CAPE = 17
EQUIP_POS_BADGE = 18
EQUIP_POS_FOOT = 19

WEAPON_TYPE_BAOTAY = 0
WEAPON_TYPE_CHAM = 1
WEAPON_TYPE_KIEM = 2
WEAPON_TYPE_DAO = 3
WEAPON_TYPE_CUNG = 4
WEAPON_TYPE_CON = 5
WEAPON_TYPE_THUONG = 6
WEAPON_TYPE_SONGDAO = 7
WEAPON_TYPE_TRUONG = 8
WEAPON_TYPE_BUT = 9
WEAPON_TYPE_DAN = 10
WEAPON_TYPE_TRAO = 11
WEAPON_TYPE_LINHNU = 12
WEAPON_TYPE_VUTIEN = 13
WEAPON_TYPE_NHAMHIEP = 14

DAME_TYPE_NGOAICONG = 1
DAME_TYPE_NOICONG = 2
DAME_TYPE_CAM = 3
DAME_TYPE_SATTHUONG = 4

-------- Faction route constants --

FACTION_THIEULAM = 1
FACTION_VODANG= 2
FACTION_NGAMI = 3
FACTION_CAIBANG = 4
FACTION_DUONGMON = 5
FACTION_DUONGGIA = 6
FACTION_NGUDOC = 7
FACTION_CONLON = 8
FACTION_MINHGIAO = 9
FACTION_THUYYEN = 10


------- Route

ROUTE_VOMONPHAI = 0

ROUTE_THIEULAM = 1
ROUTE_THIEULAM_DAO = 2
ROUTE_THIEULAM_TRUONG = 3
ROUTE_THIEULAM_QUYEN = 4

ROUTE_DUONGMON = 5
ROUTE_DUONGMON_AMKHI = 6

ROUTE_NGAMI = 7
ROUTE_NGAMI_KIEM = 8
ROUTE_NGAMI_DAN = 9

ROUTE_CAIBANG = 10
ROUTE_CAIBANG_QUYEN = 11
ROUTE_CAIBANG_BONG = 12

ROUTE_VODANG = 13
ROUTE_VODANG_KIEM = 14
ROUTE_VODANG_BUT = 15

ROUTE_DUONGGIA = 16
ROUTE_DUONGGIA_THUONG = 17
ROUTE_DUONGGIA_CUNG = 18

ROUTE_NGUDOC = 19
ROUTE_NGUDOC_HIEP = 20
ROUTE_NGUDOC_TA = 21

ROUTE_CONLON = 22
ROUTE_CONLON_THIENSU = 23

ROUTE_MINHGIAO = 24
ROUTE_MINHGIAO_THANHCHIEN = 25
ROUTE_MINHGIAO_TRANBINH = 26
ROUTE_MINHGIAO_HUYETNHAN = 27

ROUTE_THUYYEN = 28
ROUTE_THUYYEN_VUTIEN = 29
ROUTE_THUYYEN_LINHNU = 30

ROUTE_DUONGMON_NHAMHIEP = 31
ROUTE_CONLON_KIEMTON = 32

------- Player Body
BODY_NAM_TIEUCHUAN = 1
BODY_NAM_KHOINGO = 2
BODY_NU_GOICAM = 3
BODY_NU_KIEUNU = 4
