Include("\\script\\vng\\lib\\vnglib_textdata.lua")

g_szNpcName = "<color=green>Long Hæ Sø<color>: "

BHTA_SEASON = 1

BHTA_REGISTER_REQUIRE_TONG_LEVEL = 5
BHTA_REGISTER_REQUIRE_LEADER_LEVEL = 1096
BHTA_REGISTER_REQUIRE_MEMBER_LEVEL = 994

BHTA_REGISTER_REQUIRE_LEADER_ASSIGN_TIME = 7 -- days
BHTA_REGISTER_REQUIRE_MEMBER_ASSIGN_TIME = 3 -- days

BHTA_MAX_ROUTER_MEMBER = 5

BHTA_MAX_FLAG_NUM = 42

BHTA_REGISTER_FILE = "bhta_register_tong_" .. BHTA_SEASON .. ".txt"
BHTA_REGISTER_FIGHT_FILE = "bhta_register_fight_" .. BHTA_SEASON .. ".txt"
BHTA_CHECKROUTE_FILE = "bhta_checkroute_" .. BHTA_SEASON .. ".txt"
BHTA_VOTE_FILE = "bhta_vote_" .. BHTA_SEASON .. ".txt"

BHTA_FLAG_TYPE_NORMAL = 2
BHTA_FLAG_TYPE_NGUYEN_SOAI = 2

BHTA_MAX_NGUYENSOAI_NUMBER = 2

BHTA_REGISTER_START_DATE = 20201225
BHTA_REGISTER_END_DATE = 20201230

BHTA_GIVE_FLAG_START_DATE = 20210105
BHTA_GIVE_FLAG_END_DATE = 20210106
