-- Translife task
TASKID_TRANSLIFE = 1538
TASK_TRANSLIFE_BYTE_COUNT = 1
TASK_TRANSLIFE_BYTE_ROUTE = 2
TASKID_REBORN1 = 2687


-- Hoa canh
TASKID_FAIR_VALUE = 3510
TASKID_FAIR_UP_FLAG = 3511
TASKID_FAIR_UP_TIMESTAMP = 3599

TASKID_FACTION_POINT = 336

TASKID_PHONGHOA_POINT = 3407
TASKID_BOOK_POPUR2_TOTAL = 3408
TASKID_BOOK_POPUR2 = 3409

TASKID_BATTLE_HONOR = 701
TASKID_BATTLE_RANK = 704
TASKID_BATTLE_POINT = 707

----- §ua top
TASKID_TOP_AWARD_FLAG = 5000
-- §Þnh d¹ng task: aaaabc => a = l­u ®iÓm cèng hiÕn, b = l­u tr¹ng th¸i nhËn th­ëng thµnh viªn, c = tr¹ng th¸i nhËn th­ëng bang chñ
TASKID_TOP_BANG = 5001
TASKID_TOP_LEVEL_AWARD = 5002
TASKID_NEWPLAYER_AWARD_REBORN = 5003

-- Top 1 m«n ph¸i
TASK_TOP_BIT_AWARD_FACTION1 = 1
-- Top 1 nh©n vËt ®¹t c«ng tr¹ng x
TASK_TOP_BIT_AWARD_HONOR1 = 2
-- Top 2 nh©n vËt ®¹t c«ng tr¹ng y mçi phe
TASK_TOP_BIT_AWARD_HONOR2 = 3
-- Top 3 nh©n vËt ®¹t chuyÓn sinh z ®Çu tiªn
TASK_TOP_BIT_AWARD_REBORN3 = 4

TASKID_SERVER = 5004 -- Luu Server Id hien tai cua Player
TASKID_SERVER_LOGIN = 5005
TASKID_CHANGE_SERVER_REG_TIME = 5006
TASKID_NEWSERVER_SET_QUANCONG = 5007

TASKID_GIFT_CODE = 5008
TASK_GIFTCODE_BIT_NEWPLAYER = 2

--- Task for change server
TASK_SERVER_BYTE_CURRENT_SERVER_ID = 1
TASK_SERVER_BYTE_NEW_SERVER_ID = 2 -- Luu id server player dang ky chuyen den
TASK_SERVER_BYTE_LAST_SERVER_ID = 3 -- L­u id cña server ban ®Çu - gÇn nhÊt (Server tr­íc khi chuyÓn)

-- Task ®iÓm tÝch lòy tiªu xu cña ng­êi ch¬i VIP
TASKID_EVENT_SPEND_COIN = 5009
TASKID_EVENT_SPEND_COIN_STATUS_START = 5010
TASKID_EVENT_SPEND_COIN_STATUS_END = 5019

TASKID_KSG_NEWPLAYER = 5020
TASKID_KSG_NEWPLAYER_BYTE_FACTION_SUPPORT = 1
TASKID_KSG_NEWPLAYER_BYTE_DAILY_GIFT = 2
TASKID_KSG_NEWPLAYER_BYTE_WEEKLY_GIFT = 3

TASKID_INTIMATE_POINT = 5021

TASKID_COMPENSATION = 5022
TASKID_COMPENSATION_BIT_HIEPLO_30_05 = 1
TASKID_COMPENSATION_BIT_HIEPLO_02_06 = 2
TASKID_COMPENSATION_BIT_HONOR_05_07 = 3
TASKID_COMPENSATION_BIT_HONOR_19_07 = 4
TASKID_COMPENSATION_BIT_FIX_SPEND_COIN = 5
TASKID_COMPENSATION_BIT_BUG_5DOC = 6
TASKID_COMPENSATION_BIT_BUG_15000_NANGDONG = 7
TASKID_COMPENSATION_BIT_BUG_CS_1 = 8
TASKID_COMPENSATION_BIT_BUG_CS_2 = 9
TASKID_COMPENSATION_BIT_BUG_CS_3 = 10
TASKID_COMPENSATION_BIT_BUG_CS_4 = 11
TASKID_COMPENSATION_BIT_BUG_CS_5 = 12
TASKID_COMPENSATION_BIT_BUG_CS_6 = 13
TASKID_COMPENSATION_BIT_BUG_CS_7 = 14
TASKID_COMPENSATION_BIT_BUG_TMT = 15
TASKID_COMPENSATION_BIT_BUG_CS_8 = 16
TASKID_COMPENSATION_BIT_BUG_KND = 17
TASKID_COMPENSATION_BIT_BAOTRI_2808 = 18
TASKID_COMPENSATION_BIT_MERGE_SERVER = 19
TASKID_COMPENSATION_BIT_BUG_NGAN_PHIEU = 20
TASKID_COMPENSATION_BIT_TEMP_BAN = 21
TASKID_COMPENSATION_BIT_BUG_0410 = 22
TASKID_COMPENSATION_BIT_MERGE_SERVER1 = 23
TASKID_COMPENSATION_BIT_MERGE_SERVER2 = 24
TASKID_COMPENSATION_BIT_TL0412 = 25
TASKID_COMPENSATION_BIT_MERGE_SERVER3 = 26
TASKID_COMPENSATION_FIX_HOACANH = 27
TASKID_COMPENSATION_BIT_MERGE_SERVER4 = 28

-- B¸ch b¶o r­¬ng
TASKID_EVENT_BACHBAORUONG = 5023

TASKID_EVENT_MONTHLY_VERSION = 5024

TASKID_EVENT_NGANPHIEU_VERSION = 5025
TASKID_EVENT_NGANPHIEU_POINT = 3139

TASKID_TUIQUA_VOLAM_NUM = 5026
TASKID_TUIQUA_VOLAM_VERSION = 5027

TASKID_EVENT_MONTHLY_ITEM1 = 5028
TASKID_EVENT_MONTHLY_ITEM2 = 5029
TASKID_EVENT_MONTHLY_ITEM3 = 5030
TASKID_EVENT_MONTHLY_ACCUMULATE = 5031

TASKID_EVENT_MONTHLY_BIT_ACCUMULATE1 = 1
TASKID_EVENT_MONTHLY_BIT_ACCUMULATE2 = 2

TASKID_EVENT_SPEND_COIN_VERSION = 5032


-- Tu Bao Trai
TASKID_TUBAOTRAI_VERSION = 5033
TASKID_TUBAOTRAI_AWARD = 5034 --  ChØ dïng set task bit
TASKID_TUBAOTRAI_LOTTERY = 5035
TASKID_TUBAOTRAI_LOTTERY_NUM = 5036

TASKID_TUBAOTRAI_BIT_VIP_GIFT = 1 -- bit 2 trë lªn dïng cho kiÓm tra tr¹ng th¸i nhËn th­ëng mèc (kh«ng ®­îc dïng bit 2 trë lªn)

-- Tu LuyÖn Ch©u
TASKID_TULUYENCHAU_LINHKHI = 5037

-- Phô Tu
TASKID_PHUTU_ROUTE = 5038
TASKID_PHUTU_LAST_CHANGE_ROUTE = 5039
TASKID_PHUTU_BYTE_ROUTE1 = 1
TASKID_PHUTU_BYTE_ROUTE2 = 2
TASKID_PHUTU_BYTE_ROUTE3 = 3
TASKID_PHUTU_BYTE_ORIGIN_ROUTE = 4

TASKID_PHUTU_TRANPHAI = 5040
TASKID_PHUTU_BYTE_TRANPHAI1 = 1
TASKID_PHUTU_BYTE_TRANPHAI2 = 2
TASKID_PHUTU_BYTE_TRANPHAI3 = 3
TASKID_PHUTU_BYTE_ORIGIN_TRANPHAI = 4

TASKID_BACKUP_NGANPHIEU = 5041
TASKID_NSMM_COUNT = 5042

--- BHTA
TASKID_BHTA = 5043

TASKID_BHTA_BYTE_GET_FLAG = 1
TASKID_BHTA_BYTE_REGISTER_FIGHT = 3

TASKID_LIMIT_DHC = 5044
TASKID_LIMIT_LSB = 5045
TASKID_LIMIT_VKT = 5046

TASKID_LIMIT_SERVER_TEST = 5047 -- Task bit
TASKID_LIMIT_SERVER_TEST_BIT_THDC = 1 -- Limit 100 Th­¬ng H¶i Ch©u 1 nh©n vËt
TASKID_LIMIT_SERVER_TEST_BIT_CLEAR_OLD_ITEM = 2 -- Limit 100 Th­¬ng H¶i Ch©u 1 nh©n vËt

---- Access code
TASK_ACCESS_CODE_TUBAOTRAI = 41

